import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getSupabaseClient } from '../../lib/supabase/client'

export type PublicCheckinData = { activity: { title: string; activity_date: string; scheduled_start_at: string; scheduled_end_at: string; venue: { name: string; region: string; district: string } }; members: Array<{ id: string; display_name: string; level: number; plan_id: string; plan_code: string; start_at: string; end_at: string; amount: number }> }

export function useSelfCheckinAdmin(activityId: string) { return useQuery({ queryKey: ['self-checkin-admin', activityId], queryFn: async () => { const { data, error } = await getSupabaseClient().rpc('get_self_checkin_admin_v1', { target_activity_id: activityId }); if (error || !data) throw error ?? new Error('SELF_CHECKIN_ADMIN_FAILED'); return data as { is_open: boolean; eligible: boolean; activity_enabled: boolean } } }) }
export function useOpenSelfCheckin(activityId: string) { const qc=useQueryClient(); return useMutation({ mutationFn: async () => { const { data,error }=await getSupabaseClient().rpc('open_self_checkin_v1',{target_activity_id:activityId}); if(error||!data) throw error??new Error('OPEN_FAILED'); return String(data) }, onSuccess:()=>qc.invalidateQueries({queryKey:['self-checkin-admin',activityId]}) }) }
export function useCloseSelfCheckin(activityId: string) { const qc=useQueryClient(); return useMutation({ mutationFn: async () => { const {error}=await getSupabaseClient().rpc('close_self_checkin_v1',{target_activity_id:activityId}); if(error) throw error }, onSuccess:()=>qc.invalidateQueries({queryKey:['self-checkin-admin',activityId]}) }) }
export function usePublicCheckin(token: string) { return useQuery({ queryKey:['public-checkin',token], queryFn:async()=>{const {data,error}=await getSupabaseClient().rpc('get_public_self_checkin_v1',{target_token:token});if(error||!data)throw error??new Error('INVALID_LINK');return data as PublicCheckinData} }) }
export function useCompletePublicCheckin(token:string){const qc=useQueryClient();return useMutation({mutationFn:async(memberId:string)=>{const{data,error}=await getSupabaseClient().rpc('complete_public_self_checkin_v1',{target_token:token,target_member_id:memberId});if(error||!data)throw error??new Error('CLAIM_FAILED');return data as {display_name:string;transaction_id:string;amount:number}},onSuccess:()=>qc.invalidateQueries({queryKey:['public-checkin',token]})})}
