import { type FormEvent, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useActivityCenter } from '../activities/activityCenterApi'
import { useAuth } from '../auth/AuthProvider'
import { useAccountSettingsData, useClubSettingsData, useUpdateOrganization, useUpdateProfile } from './settingsApi'
import { VenuesSection } from './VenuesSection'
import { TemplatesSection } from './TemplatesSection'
import { ContentNavigation } from '../../app/ContentWorkspace'
import { UNARCHIVED_ACTIVITY_LIMIT } from '../activities/activityLimits'

function LoadingState({ label }: { label: string }) { return <div className="centered-state">載入{label}…</div> }
function ErrorState({ label, retry }: { label: string; retry: () => void }) { return <div className="centered-state"><p>目前無法載入{label}。</p><button className="secondary-button" onClick={retry}>重新整理</button></div> }

export function AccountSettingsPage() {
  const auth = useAuth(); const navigate = useNavigate(); const settings = useAccountSettingsData(auth.user?.id); const updateProfile = useUpdateProfile(auth.user?.id); const [message, setMessage] = useState('')
  if (settings.isLoading) return <LoadingState label="帳號設定" />
  if (settings.isError || !settings.data) return <ErrorState label="帳號設定" retry={() => { void settings.refetch() }} />
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('displayName')).trim(); if (!name) return; try { await updateProfile.mutateAsync(name); setMessage('顯示名稱已更新。') } catch { setMessage('無法更新顯示名稱。') } }
  async function signOut() { await auth.signOut(); navigate('/login', { replace: true }) }
  return <div className="settings-page account-settings-page"><ContentNavigation backTo="/activities" context="帳號設定" /><div className="settings-layout"><main className="settings-content">{message && <p className="action-message" role="status">{message}</p>}<div className="settings-general-layout account-settings-layout"><div className="settings-general-primary"><section><header className="settings-inline-heading"><h2>個人資料</h2><p>所有球團共用的帳號資訊</p></header><form className="settings-form" onSubmit={save}><label><span className="field-label">帳號</span><input readOnly value={settings.data.username_normalized} /></label><label><span className="field-label">暱稱<span className="required-mark" aria-hidden="true">*</span></span><input name="displayName" required minLength={2} maxLength={20} defaultValue={settings.data.display_name} placeholder="例如：小羽" /></label><footer><button className="primary-button" disabled={updateProfile.isPending}>儲存個人資料</button></footer></form></section><section><header className="settings-inline-heading"><h2>帳號操作</h2><p>結束目前裝置的登入狀態</p></header><button className="secondary-button account-sign-out" onClick={signOut}>登出目前帳號</button></section></div></div></main></div></div>
}

type ClubSection = 'general' | 'venues' | 'templates'
export function ClubSettingsPage() {
  const auth = useAuth(); const [searchParams] = useSearchParams(); const settings = useClubSettingsData(auth.user?.id); const activityCenter = useActivityCenter(); const updateOrganization = useUpdateOrganization(); const requestedSection = searchParams.get('section'); const initialSection: ClubSection = requestedSection === 'templates' ? 'templates' : requestedSection === 'venues' ? 'venues' : 'general'; const [section, setSection] = useState<ClubSection>(initialSection); const [message, setMessage] = useState(''); const [linePayDemoEnabled, setLinePayDemoEnabled] = useState<boolean | null>(null); const [paymentTestMessage, setPaymentTestMessage] = useState('')
  if (settings.isLoading) return <LoadingState label="球團設定" />
  if (settings.isError || !settings.data) return <ErrorState label="球團設定" retry={() => { void settings.refetch() }} />
  const data = settings.data
  const demoEnabled = linePayDemoEnabled ?? data.organization.line_pay_demo_enabled
  async function saveClub(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await updateOrganization.mutateAsync({ ...data.organization, name: String(form.get('name')).trim(), default_contact_info: String(form.get('contact')).trim() || null, default_shuttlecock: String(form.get('shuttlecock')).trim() || null, description: String(form.get('description')).trim() || null }); setMessage('球團資料已儲存。') } catch { setMessage('無法儲存球團資料，請稍後再試。') } }
  async function savePayment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const enabled = form.get('enabled') === 'on'; const merchantName = String(form.get('merchantName') ?? '').trim(); if (enabled && !merchantName) return setMessage('啟用 Demo 前請填寫 Demo 商店名稱。'); const merchantId = data.organization.line_pay_demo_merchant_id ?? `DEMO-${crypto.randomUUID().slice(0, 8).toUpperCase()}`; try { await updateOrganization.mutateAsync({ ...data.organization, line_pay_demo_enabled: enabled, line_pay_demo_merchant_name: merchantName || null, line_pay_demo_merchant_id: merchantId }); setMessage(enabled ? 'LINE Pay Demo 已啟用。' : 'LINE Pay Demo 已停用。') } catch { setMessage('無法儲存 Demo 設定，請稍後再試。') } }
  const settingTabs = ([['general','一般設定'],['venues','我的球館'],['templates','活動範本']] as Array<[ClubSection,string]>).map(([id,label]) => ({ id, label }))
  return <div className="settings-page"><ContentNavigation backTo="/activities" context="球團設定" tabs={settingTabs} activeTab={section} onTabChange={(value) => { setSection(value as ClubSection); setMessage('') }} /><div className="settings-layout"><main className="settings-content">{message && <p className="action-message" role="status">{message}</p>}
    {section === 'general' && <div className="settings-general-layout"><div className="settings-general-primary">
      <section><header className="settings-inline-heading"><h2>球團資料</h2><p>建立活動時自動帶入的預設資料</p></header><form className="settings-form" onSubmit={saveClub}><label><span className="field-label">球團名稱<span className="required-mark" aria-hidden="true">*</span></span><input name="name" required maxLength={40} defaultValue={data.organization.name} placeholder="例如：星期三羽球團" /></label><label><span className="field-label">預設團主聯絡資料</span><input name="contact" maxLength={100} defaultValue={data.organization.default_contact_info ?? ''} placeholder="例如：LINE ID：badminton99" /></label><label><span className="field-label">預設指定用球</span><input name="shuttlecock" maxLength={50} defaultValue={data.organization.default_shuttlecock ?? ''} placeholder="例如：RSL 4 號" /></label><label><span className="field-label">球團簡介</span><textarea name="description" maxLength={500} defaultValue={data.organization.description ?? ''} placeholder="例如：每週三晚間固定開團" /></label><footer><button className="primary-button" disabled={updateOrganization.isPending}>儲存球團資料</button></footer></form></section>
      <section><header className="settings-inline-heading"><h2>付款與串接</h2><p>LINE Pay 模擬付款展示設定</p></header><form className="settings-form" onSubmit={savePayment}><label className="settings-toggle settings-line-pay-toggle"><span><strong>LINE Pay Demo</strong><small>{demoEnabled ? '已啟用，可設定展示商店與測試付款' : '啟用後，活動可使用自助付款展示流程'}</small></span><input name="enabled" type="checkbox" checked={demoEnabled} onChange={(event) => { setLinePayDemoEnabled(event.target.checked); setPaymentTestMessage('') }} /></label>{demoEnabled && <div className="settings-demo-fields"><label><span className="field-label">Demo 商店名稱<span className="required-mark" aria-hidden="true">*</span></span><input name="merchantName" required maxLength={60} defaultValue={data.organization.line_pay_demo_merchant_name ?? ''} placeholder="例如：星期三羽球團 Demo 商店" /></label><label><span className="field-label">Demo Merchant ID</span><input readOnly value={data.organization.line_pay_demo_merchant_id ?? '儲存設定後由系統產生'} /></label><button type="button" className="secondary-button" onClick={() => setPaymentTestMessage('測試付款成功，這是展示流程，不會產生真實交易。')}>測試付款</button>{paymentTestMessage && <p className="settings-payment-test-result" role="status">{paymentTestMessage}</p>}</div>}<footer><button className="primary-button" disabled={updateOrganization.isPending}>儲存付款設定</button></footer></form></section>
    </div><aside className="settings-usage-rail"><header className="settings-inline-heading"><h2>使用量與限制</h2><p>目前球團資源</p></header><dl className="usage-list"><div><dt>未封存活動</dt><dd>{activityCenter.data?.unarchivedCount ?? 0} / {UNARCHIVED_ACTIVITY_LIMIT}</dd></div><div><dt>活動範本</dt><dd>{data.counts.templates}</dd></div><div><dt>私人球館</dt><dd>{data.counts.venues}</dd></div><div><dt>球團管理員</dt><dd>1</dd></div><div><dt>雲端同步</dt><dd className="success-text">正常</dd></div></dl><p>僅顯示產品限制，不包含底層資料庫或 API 用量。</p></aside></div>}
    {section === 'venues' && <VenuesSection onMessage={setMessage} />}
    {section === 'templates' && <TemplatesSection onMessage={setMessage} />}
  </main></div></div>
}

export const SettingsPage = ClubSettingsPage
