import { type FormEvent, useMemo, useState } from 'react'
import { taiwanDistricts, taiwanRegions } from '../activities/taiwanDistricts'
import { type VenueData, type VenueInput, useDeleteVenue, useSaveVenue, useVenues } from './settingsApi'

type EditorState = { venue?: VenueData; copy?: boolean }
type SortMode = 'recent' | 'name' | 'usage'

export function VenueEditor({ state, venues, onClose, onSaved }: { state: EditorState; venues: Array<Pick<VenueData, 'id' | 'name' | 'region' | 'district'>>; onClose: () => void; onSaved: (message: string, input: VenueInput) => void }) {
  const saveVenue = useSaveVenue()
  const initialRegion = state.venue?.region ?? '臺北市'
  const [region, setRegion] = useState(initialRegion)
  const [duplicate, setDuplicate] = useState<{ existing: Pick<VenueData, 'id' | 'name' | 'region' | 'district'>; input: VenueInput } | null>(null)
  const [message, setMessage] = useState('')

  async function persist(input: VenueInput, mode: 'normal' | 'add-anyway' | 'update-existing' = 'normal') {
    const match = venues.find((venue) => venue.id !== input.id && venue.name.trim().toLocaleLowerCase() === input.name.trim().toLocaleLowerCase() && venue.region === input.region && venue.district === input.district)
    if (match && mode === 'normal') { setDuplicate({ existing: match, input }); return }
    const payload = mode === 'update-existing' && match ? { ...input, id: match.id } : input
    try { await saveVenue.mutateAsync(payload); onSaved(payload.id ? '球館資料已更新。' : '球館已新增。', payload) } catch { setMessage('目前無法儲存球館，請稍後再試。') }
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    void persist({ id: state.copy ? undefined : state.venue?.id, name: String(form.get('name')).trim(), region, district: String(form.get('district')), address: String(form.get('address')).trim() || null, floor_type: String(form.get('floorType')).trim() || null, note: String(form.get('note')).trim() || null })
  }

  return <div className="panel-backdrop" role="presentation"><section className="side-panel venue-editor" role="dialog" aria-modal="true" aria-labelledby="venue-editor-title"><header><h2 id="venue-editor-title">{state.copy ? '複製球館' : state.venue ? '編輯球館' : '新增球館'}</h2><button className="icon-button" onClick={onClose} aria-label="關閉">×</button></header><form className="form-stack" onSubmit={submit}><label><span className="field-label">球館名稱<span className="required-mark" aria-hidden="true">*</span></span><input name="name" required maxLength={60} autoFocus defaultValue={state.copy ? `${state.venue?.name ?? ''} 副本` : state.venue?.name ?? ''} placeholder="例如：中山運動中心" /></label><div className="form-grid"><label><span className="field-label">縣市<span className="required-mark" aria-hidden="true">*</span></span><select name="region" value={region} onChange={(event) => setRegion(event.target.value)}>{taiwanRegions.map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="field-label">行政區<span className="required-mark" aria-hidden="true">*</span></span><select name="district" defaultValue={state.venue?.district ?? taiwanDistricts[initialRegion][0]} key={region}>{taiwanDistricts[region].map((value) => <option key={value}>{value}</option>)}</select></label></div><label>地址<input name="address" maxLength={120} defaultValue={state.venue?.address ?? ''} placeholder="例如：中山北路二段 44 巷 2 號" /></label><label>地板材質<input name="floorType" maxLength={30} defaultValue={state.venue?.floor_type ?? ''} placeholder="例如：木地板、PU" /></label><label>備註<textarea name="note" maxLength={200} defaultValue={state.venue?.note ?? ''} placeholder="例如：入口、停車或場地注意事項" /></label>{message && <p className="form-error">{message}</p>}<footer className="panel-actions"><button type="button" className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" disabled={saveVenue.isPending}>{saveVenue.isPending ? '儲存中…' : '儲存球館'}</button></footer></form>{duplicate && <div className="nested-confirm" role="alertdialog" aria-labelledby="duplicate-venue-title"><h3 id="duplicate-venue-title">可能已有相同球館</h3><p>「{duplicate.existing.name}」位於相同縣市與行政區。你可以更新既有資料，或仍新增一筆。</p><footer><button className="secondary-button" onClick={() => setDuplicate(null)}>返回修改</button><button className="secondary-button" onClick={() => void persist(duplicate.input, 'add-anyway')}>仍新增</button><button className="primary-button" onClick={() => void persist(duplicate.input, 'update-existing')}>更新既有</button></footer></div>}</section></div>
}

export function VenuesSection({ onMessage }: { onMessage: (message: string) => void }) {
  const venues = useVenues(); const deleteVenue = useDeleteVenue(); const [search, setSearch] = useState(''); const [sort, setSort] = useState<SortMode>('recent'); const [editor, setEditor] = useState<EditorState | null>(null); const [pendingDelete, setPendingDelete] = useState<VenueData | null>(null)
  const visible = useMemo(() => (venues.data ?? []).filter((venue) => `${venue.name}${venue.region}${venue.district}${venue.address ?? ''}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'zh-TW') : sort === 'usage' ? b.use_count - a.use_count : (b.last_used_at ?? b.updated_at).localeCompare(a.last_used_at ?? a.updated_at)), [venues.data, search, sort])
  async function confirmDelete() { if (!pendingDelete) return; try { await deleteVenue.mutateAsync(pendingDelete.id); setPendingDelete(null); onMessage('私人球館已刪除，既有活動的場地快照不受影響。') } catch { onMessage('目前無法刪除球館，請稍後再試。') } }
  return <section><div className="section-heading settings-section-heading"><div><h2>我的球館</h2><p className="muted">維護建立活動時可快速選用的私人球館。</p></div><button className="primary-button" onClick={() => setEditor({})}>＋ 新增球館</button></div><div className="venue-tools"><input aria-label="搜尋球館" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜尋名稱、地區或地址" /><select aria-label="球館排序" value={sort} onChange={(event) => setSort(event.target.value as SortMode)}><option value="recent">最近使用</option><option value="usage">使用次數</option><option value="name">名稱</option></select></div>{venues.isLoading ? <div className="centered-state compact">載入球館…</div> : venues.isError ? <div className="empty-state compact"><p>目前無法載入私人球館。</p><button className="secondary-button" onClick={() => void venues.refetch()}>重新整理</button></div> : visible.length === 0 ? <div className="empty-state compact"><h3>{search ? '沒有符合的球館' : '尚未建立私人球館'}</h3><p>{search ? '請調整搜尋條件。' : '新增後可在建立活動時直接選用。'}</p></div> : <div className="venue-list">{visible.map((venue) => <article key={venue.id}><div><strong>{venue.name}</strong><span>{venue.region}{venue.district}{venue.address ? ` · ${venue.address}` : ''}</span><small>{venue.floor_type || '未填地板材質'} · 使用 {venue.use_count} 次{venue.last_used_at ? ` · 最近使用 ${new Intl.DateTimeFormat('zh-TW', { dateStyle: 'medium' }).format(new Date(venue.last_used_at))}` : ''}</small>{venue.note && <small>備註：{venue.note}</small>}</div><div className="venue-actions"><button className="text-button" onClick={() => setEditor({ venue })}>編輯</button><button className="text-button" onClick={() => setEditor({ venue, copy: true })}>複製</button><button className="text-button danger-text" onClick={() => setPendingDelete(venue)}>刪除</button></div></article>)}</div>}{editor && <VenueEditor state={editor} venues={venues.data ?? []} onClose={() => setEditor(null)} onSaved={(message) => { setEditor(null); onMessage(message) }} />}{pendingDelete && <div className="panel-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-venue-title"><h2 id="delete-venue-title">刪除「{pendingDelete.name}」？</h2><p>球館會從「我的球館」移除，但不會改動既有活動保存的場地資料。</p><footer><button className="secondary-button" onClick={() => setPendingDelete(null)}>返回</button><button className="danger-button" disabled={deleteVenue.isPending} onClick={() => void confirmDelete()}>刪除球館</button></footer></section></div>}</section>
}
